
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *Main Class that contains the main frame includes two jPanels. 
 * @author Kevin
 */
public class GambleTable extends javax.swing.JFrame {
    
    Random rand = new Random();
    
    private int[] myRollsArray = new int[6];     //array to contain my roll result
    private int myRollsTotal=0;
    private int myGuess;
    private int myWagerbit;
    private int myCash=100;
    
    /**Class variable: an ArrayList that holds Photos Objects according to my rolls number.  */
    ArrayList <Photos> myImagesArrayList = new ArrayList<>();
    
    private int[] comRollsArray = new int[6];    //array to contain computer's roll result
    private int comRollsTotal;
    private int comGuess;
    private int comWagerbit;
    private int comCash=100;
    
    /**Class variable: an ArrayList that holds Photos Objects according to computer rolls number.  */
    ArrayList <Photos> comImagesArrayList = new ArrayList<>();
   

    /**
     * Constructor of main frame class to Creates new form GambleTable object. At start to see the frame. 
     */
    public GambleTable() {
        initComponents();
       
    }
    
    /**Inner method built in my_jPanel's constructor to extract every photos object stored img variable in myImagesArrayList and display them on my_jPanel.
     * @param g represents Graphics on jPanel for Photos object to display Photos object's image on jPanel.  */
    public void redrawMyPanel(java.awt.Graphics g)
    {     
          int y = 100;
          
          for(int x=0; x<myImagesArrayList.size(); x++)
      {
            myImagesArrayList.get(x).displayMyPhoto(g,(x*130),y);
      }
          
          my_jPanel.repaint();
              
           
    }
    
    /**
     * inner method built in com_jPanel constructor to extract every photos object stored img variable in comImagesArrayList and display them on com_jPanel.
     * @param g represents Graphics on jPanel for Photos object to display Photos object's image on jPanel.
     */
    public void redrawComPanel(Graphics g)   //this redraw is built in com_jPanel inner Class: Graphics g is on com_jPanel
    {     
         int y= 100;
         for(int x=0; x<comImagesArrayList.size(); x++)
      {
            comImagesArrayList.get(x).displayComPhoto(g,(x*130),y);
      }   
        
         com_jPanel.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        my_jPanel = new javax.swing.JPanel(){     //AnonInner Class method by right click jPanel in design mode, choose customer code
            public void paintComponent(java.awt.Graphics g)
            {
                super.paintComponent(g);

                redrawMyPanel(g);
            }
        };
        myGuess_jSlider = new javax.swing.JSlider();
        myGuessjLabel = new javax.swing.JLabel();
        myWager_jSlider = new javax.swing.JSlider();
        myWagerjLabel = new javax.swing.JLabel();
        myRolljLabel = new javax.swing.JLabel();
        myCash_jLabel = new javax.swing.JLabel();
        play_jButton = new javax.swing.JButton();
        myCashNumber_jLabel = new javax.swing.JLabel();
        myResult_jLabel = new javax.swing.JLabel();
        myGuessNumber_jLabel = new javax.swing.JLabel();
        myWagerNumber_jLabel = new javax.swing.JLabel();
        gOver_jLabel = new javax.swing.JLabel();
        com_jPanel = new javax.swing.JPanel(){
            public void paintComponent(java.awt.Graphics g)
            {
                super.paintComponent(g);

                redrawComPanel(g);
            }

        };
        comRoll_jLabel = new javax.swing.JLabel();
        comResult_jLabel = new javax.swing.JLabel();
        comCash_jLabel = new javax.swing.JLabel();
        comCashNumber_jLabel = new javax.swing.JLabel();
        comGuess_jLabel = new javax.swing.JLabel();
        comWager_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        my_jPanel.setBackground(new java.awt.Color(102, 204, 255));

        myGuess_jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                myGuess_jSliderStateChanged(evt);
            }
        });

        myGuessjLabel.setBackground(java.awt.SystemColor.activeCaptionText);
        myGuessjLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        myGuessjLabel.setForeground(new java.awt.Color(51, 51, 51));
        myGuessjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myGuessjLabel.setText("My Prediction of Total Roll ");

        myWager_jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                myWager_jSliderStateChanged(evt);
            }
        });

        myWagerjLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        myWagerjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myWagerjLabel.setText("My Wager of  $ bit");

        myRolljLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        myRolljLabel.setText("MY ROLL");

        myCash_jLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        myCash_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myCash_jLabel.setText("MY CASH");

        play_jButton.setText("MY PLAY");
        play_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                play_jButtonMousePressed(evt);
            }
        });

        myCashNumber_jLabel.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        myCashNumber_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myCashNumber_jLabel.setText("$ 100");

        myResult_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myResult_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        myResult_jLabel.setText("my result");

        myGuessNumber_jLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        myGuessNumber_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myGuessNumber_jLabel.setText("0");

        myWagerNumber_jLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        myWagerNumber_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myWagerNumber_jLabel.setText("$ 0");

        gOver_jLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        gOver_jLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout my_jPanelLayout = new javax.swing.GroupLayout(my_jPanel);
        my_jPanel.setLayout(my_jPanelLayout);
        my_jPanelLayout.setHorizontalGroup(
            my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(my_jPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myGuess_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myGuessjLabel))
                .addGap(33, 33, 33)
                .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myWagerjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myWager_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(play_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(my_jPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(myGuessNumber_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(myWagerNumber_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, my_jPanelLayout.createSequentialGroup()
                .addGap(56, 86, Short.MAX_VALUE)
                .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, my_jPanelLayout.createSequentialGroup()
                        .addComponent(myRolljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(myResult_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301)
                        .addComponent(myCash_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(myCashNumber_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, my_jPanelLayout.createSequentialGroup()
                        .addComponent(gOver_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))))
        );
        my_jPanelLayout.setVerticalGroup(
            my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, my_jPanelLayout.createSequentialGroup()
                .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(my_jPanelLayout.createSequentialGroup()
                        .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(myRolljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myCash_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myCashNumber_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(gOver_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, my_jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(myResult_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, my_jPanelLayout.createSequentialGroup()
                        .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(my_jPanelLayout.createSequentialGroup()
                                .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(myGuessjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(myWagerjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(myGuess_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(myWager_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, my_jPanelLayout.createSequentialGroup()
                        .addComponent(play_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(my_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myGuessNumber_jLabel)
                    .addComponent(myWagerNumber_jLabel))
                .addGap(18, 18, 18))
        );

        com_jPanel.setBackground(new java.awt.Color(255, 153, 204));

        comRoll_jLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        comRoll_jLabel.setText("COMPUTER ROLL");

        comResult_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comResult_jLabel.setText("Computer Result");

        comCash_jLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        comCash_jLabel.setText("COMPUTER CASH");

        comCashNumber_jLabel.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        comCashNumber_jLabel.setText("$ 100");

        comGuess_jLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comGuess_jLabel.setText("computer guess");

        comWager_jLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comWager_jLabel.setText("computer wager bit");

        javax.swing.GroupLayout com_jPanelLayout = new javax.swing.GroupLayout(com_jPanel);
        com_jPanel.setLayout(com_jPanelLayout);
        com_jPanelLayout.setHorizontalGroup(
            com_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(com_jPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(com_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(com_jPanelLayout.createSequentialGroup()
                        .addComponent(comRoll_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(comResult_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(comCash_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(comCashNumber_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(com_jPanelLayout.createSequentialGroup()
                        .addComponent(comGuess_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(comWager_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        com_jPanelLayout.setVerticalGroup(
            com_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(com_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(com_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(com_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(com_jPanelLayout.createSequentialGroup()
                            .addGroup(com_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comResult_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comCash_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4))
                        .addComponent(comRoll_jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comCashNumber_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(com_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comGuess_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comWager_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(com_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(my_jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(my_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(com_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Hook Method called when I change myGuess_jSlider to start to make a guess of total roll numbers. This jSlider's value is reflected by the jLabel below it.   */
    private void myGuess_jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_myGuess_jSliderStateChanged
         myGuess_jSlider.setMaximum(36);         //limit the value of this slider between 6 and 36
         myGuess_jSlider.setMinimum(6); 
         
         myGuess = myGuess_jSlider.getValue();        //assign slider reading to class variable myGuess
         myGuessNumber_jLabel.setText(myGuess+"");               //concatnate the int to String by +
    }//GEN-LAST:event_myGuess_jSliderStateChanged

    /**HOOK Method called when I change myWager_jSlider to start to bit on $. This jSlider's value is reflected to the jLabel below it.   */
    private void myWager_jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_myWager_jSliderStateChanged
        myWager_jSlider.setMinimum(1);
        myWager_jSlider.setMaximum(myCash);
        
        myWagerbit = myWager_jSlider.getValue();
        myWagerNumber_jLabel.setText("$ "+myWagerbit);
        
    }//GEN-LAST:event_myWager_jSliderStateChanged
    
    /**Hook Method is called when the play button is pressed. First to roll dice for me and computer.
     * second to add Photo objects into diceImageArrayList that holds Photo objects with specific images according to the dice number(integer) passed in from its constructor. */
    private void play_jButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_play_jButtonMousePressed
        /**clear the Photo ArrayList from last run for me. To make image spaces for this run. */       
            myImagesArrayList.clear();
        
        /**clear the Photo ArrayList from last run for computer. */
            comImagesArrayList.clear();


        //I roll 6 dice and store the values in my array
        for(int i=0; i<myRollsArray.length; i++)
        {
            myRollsArray[i]=rand.nextInt(6)+1;      //I get random roll for each dice between 1-6, and add them into the myRollarray
        }
        
        //computer rolls 6 dice and store the values in computer's array
        for(int j=0; j<comRollsArray.length; j++)
        {
            comRollsArray[j]= rand.nextInt(6)+1;   //computer get random rolls for each dice between 1-6
        }
        
        //at this time, we have int value in rollArray, but nothing in photoArrayList, so we add photos into photoArrayList according to the int value in rollArray
        //create dice images for me in myImagesArrayList according to the roll number passed in stored in myRollsArray one to one matching to each other
        for(int s=0; s<myRollsArray.length; s++)
        {
             myImagesArrayList.add(new Photos(myRollsArray[s]));
        }
        
        //create dice images for the computer in comDiceImagesArray according to the roll number passed in stored in comRollsArray one to one matching to each other
        for(int t=0; t<comRollsArray.length; t++)         //use comRollsArrray.length=6, this time comImagesArrayList.size=0
        {
             comImagesArrayList.add(new Photos(comRollsArray[t]));
        }
        
        
        //calculate my roll numbers total
        for(int i=0; i<myRollsArray.length; i++)
        {
              myRollsTotal += myRollsArray[i];
              
        }
        myResult_jLabel.setText("I rolls total as "+myRollsTotal);   //display my result in my jLabel
         
        
        //calculate computer roll numbers total
        for(int i=0; i<comRollsArray.length; i++)
        {
               comRollsTotal += comRollsArray[i];
        }
        comResult_jLabel.setText("Computer rolls total as "+comRollsTotal);
        
        
        //computer make a guess of total roll numbers between 6 and 36
        comGuess = rand.nextInt(31)+6;
        comGuess_jLabel.setText("Computer guess the total rolls could be "+comGuess);    //computer make a 
        
        //computer make a wiger bit by a random $ between $1 and $comCash
        comWagerbit = rand.nextInt(Math.abs(comCash)+10)+1;
        comWager_jLabel.setText("Computer made wager bit: "+ comWagerbit);
        
        
        /**method to decide the result of each run to distribute the cash between me and computer.  */
        if(myCash>0 && comCash>0)    //if both have cash positive, keep playing
        {
           if(myGuess>myRollsTotal && comGuess<comRollsTotal)    //I lose, com win
           {
                myCash -= myWagerbit;         //I lose my bit, renew my cash amount
                comCash += comWagerbit;      //com wins its bit, renew its cash amount
                myCashNumber_jLabel.setText("$ "+myCash);          //display renewed $cash
                comCashNumber_jLabel.setText("$ "+ comCash);
                
                my_jPanel.repaint();
                com_jPanel.repaint();
           }
           else if(myGuess<myRollsTotal && comGuess>comRollsTotal)   //I win, com lose
           {
                myCash += myWagerbit;        //I win my bit
                comCash -= comWagerbit;         //com lose its bit
                comCashNumber_jLabel.setText("$ "+ comCash);     //display new $ cash
                myCashNumber_jLabel.setText("$ "+myCash);
              
                my_jPanel.repaint();
                com_jPanel.repaint();
            }
           else if(myGuess<myRollsTotal && comGuess<comRollsTotal)
           {
               if(Math.abs(myGuess-myRollsTotal)<Math.abs(comGuess-comRollsTotal))
               {        //I win
                    myCash += myWagerbit;        //I win my bit
                    comCash -= comWagerbit;         //com lose its bit
                    comCashNumber_jLabel.setText("$ "+ comCash);     //display new $ cash
                    myCashNumber_jLabel.setText("$ "+myCash);
                    
                    my_jPanel.repaint();
                    com_jPanel.repaint();
               }
               else
               {     //com win
                    myCash -= myWagerbit;         //I lose. myCash - my bit
                    comCash += comWagerbit;      //com wins. comCash +its bit
                    myCashNumber_jLabel.setText("$ "+myCash);          //display new $cash
                    comCashNumber_jLabel.setText("$ "+ comCash);
                    
                    my_jPanel.repaint();
                    com_jPanel.repaint();
               }
           }
        
        }   
        else{        //if not both have positive cash on hand, final result 
                if(myCash>0 && comCash<0)      //Game over: I win, clear old dice image, add winner image into my Photo ArrayList
                {
                      
                      myImagesArrayList.clear();             //game over, clear my Photo arrayList
                      myImagesArrayList.add(new Photos(0));    //add winner picture to my Photo arrayList
                      gOver_jLabel.setText("Game Over!");
                      
                      my_jPanel.repaint();
                      com_jPanel.repaint();
                      
                }
                else if(myCash<0 && comCash>0)   //Game over: computer win, clear old dice image, add winner image into com Photo ArrayList
                {
                      
                      comImagesArrayList.clear();
                      comImagesArrayList.add(new Photos(0));
                      gOver_jLabel.setText("Game Over!");
                      
                      my_jPanel.repaint();
                      com_jPanel.repaint();
                }
                
        }
        
        myRollsTotal =0;     //reset myRollsTotal to 0 for the next run.
        comRollsTotal=0;   //reset comRollsTotal to 0 for the next run
        
    }//GEN-LAST:event_play_jButtonMousePressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GambleTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GambleTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GambleTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GambleTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form: at start(when the main GambleTable Frame object is created)*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GambleTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comCashNumber_jLabel;
    private javax.swing.JLabel comCash_jLabel;
    private javax.swing.JLabel comGuess_jLabel;
    private javax.swing.JLabel comResult_jLabel;
    private javax.swing.JLabel comRoll_jLabel;
    private javax.swing.JLabel comWager_jLabel;
    private javax.swing.JPanel com_jPanel;
    private javax.swing.JLabel gOver_jLabel;
    private javax.swing.JLabel myCashNumber_jLabel;
    private javax.swing.JLabel myCash_jLabel;
    private javax.swing.JLabel myGuessNumber_jLabel;
    private javax.swing.JSlider myGuess_jSlider;
    private javax.swing.JLabel myGuessjLabel;
    private javax.swing.JLabel myResult_jLabel;
    private javax.swing.JLabel myRolljLabel;
    private javax.swing.JLabel myWagerNumber_jLabel;
    private javax.swing.JSlider myWager_jSlider;
    private javax.swing.JLabel myWagerjLabel;
    private javax.swing.JPanel my_jPanel;
    private javax.swing.JButton play_jButton;
    // End of variables declaration//GEN-END:variables
}
